services:
    otel-collector:
      image: otel/opentelemetry-collector:latest
      network_mode: host
      # links:
      #   - jaeger
      # ports:
      #   - "4317:4317"  # gRPC
      #   - "4318:4318"  # HTTP
      command: ["--config=/etc/otel-collector-config.yaml"]
      volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml

    jaeger:
      image: jaegertracing/all-in-one:latest
      network_mode: host
      command:
        - "--metrics-backend=prometheus"
      # ports:
      #   - "16686:16686"  # UI
      #   - "14268:14268"  # HTTP Collector
      #   - "14250:14250"  # gRPC Collector
      #   - "6831:6831/udp"  # UDP protocol for sending traces
      #   - "6832:6832/udp"  # UDP protocol for sending traces
      #
    loki:
      image: grafana/loki:latest
      container_name: loki
      network_mode: host
      # ports:
      #   - "3100:3100" # Loki HTTP API
      command: -config.file=/etc/loki/local-config.yaml
      volumes:
        - ./loki-config.yaml:/etc/loki/local-config.yaml

    promtail:
      image: grafana/promtail:latest
      container_name: promtail
      network_mode: host
      volumes:
        - /var/log:/var/log
        - ./promtail-config.yaml:/etc/promtail/config.yml
      command: -config.file=/etc/promtail/config.yml

    prometheus:
      image: prom/prometheus:latest
      network_mode: host
      # links:
      #   - otel-collector
      # ports:
      # - "9090:9090"
      volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
      image: grafana/grafana:latest
      network_mode: host
    #   # links:
    #   #   - jaeger
    #   #   - prometheus
    #   # ports:
    #   # - "3033:3000"
      volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/

