receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14317
      http:
        endpoint: 0.0.0.0:14318

  prometheus:
    config:
      scrape_configs:
        - job_name: trader
          scrape_interval: 5s
          static_configs:
            - targets: [localhost:3000]

processors:
  batch:

exporters:
  debug:
  otlp:
    endpoint: "localhost:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8887"
  otlphttp:
    endpoint: "http://localhost:3100/otlp"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug,otlp]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      # processors: [batch]
      exporters: [debug,otlphttp]
