global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
- job_name: trader
  honor_labels: true
  static_configs:
  - targets:
    - 'localhost:3000'
- job_name: node-exporter
  honor_labels: true
  static_configs:
  - targets:
    - 'localhost:9100'
- job_name: otel-collector
  static_configs:
  - targets:
    - 'localhost:8887'

- job_name: loki
  static_configs:
  - targets:
    - 'localhost:3100'
